// Generated by CoffeeScript 1.7.1
(function() {
  println("CoffeeScript is fun!");

}).call(this);

//# sourceMappingURL=coffeescript-source.coffee@source.map
// Generated by CoffeeScript 1.7.1
(function() {
  var motto;

  motto = "Stacks are fun, especially in production.";

}).call(this);

//# sourceMappingURL=stack.coffee@source.map