// Generated by CoffeeScript 1.7.1
(function() {
  println("CoffeeScript is fun!");

}).call(this);

//# sourceMappingURL=coffeescript-source.coffee@source.map
// Generated by CoffeeScript 1.7.1
(function() {
  var showDialog;

  showDialog = function(text) {
    return window.alert(text);
  };

  $("#logo").click(showDialog);

}).call(this);

//# sourceMappingURL=stack.coffee@source.map
